### ISSUE TITLE
Improvement: Typos. 

### ISSUE THREAD

**Issue by Roopatratest** [cryptokingdom/CK_Beta#11]
Give resources on character page says "mineritos". twice.
Clicking the "W" there is Crypto Kindoms FAQ, how about Crypto Kingdom´s?

**Comment by ghost** [comment]
Fixed by dev. Note: the second can be edited in browser using the wiki tools (which were fixed as part of this issue) I think it makes more sense for this to be made through the front end than to be messing around with it on the backend.
