### ISSUE TITLE
Bug:

### ISSUE THREAD

**Issue by Roopatratest** [cryptokingdom/CK_Beta#3]
Bottom left corner of the main map view, clicking the "W" goes to All Articles page, when clicking "Mytest" this comes up:
Using the URLconf defined in ck.urls, Django tried these URL patterns, in this order:
^$ [name='index']
^login/ [name='login']
^login_guest/ [name='loginGuest']
^guest_upgrade/ [name='guestUpgrade']
^signup/ [name='signup']
^logout/ [name='logout']
^chatbox/ [name='chatbox']
^edit/ [name='editCharacter']
^GET/my_character/ [name='getMyCharacter']
^admin/
data/
^wiki/
^map/
GET/\* [name='dispatcher_get']
SET/\* [name='dispatcher_set']
^convert/
^ ^$ [name='api-root']
^ ^.(?P<format>[a-z0-9]+)$ [name='api-root']
^ ^users/$ [name='user-list']
^ ^users/.(?P<format>[a-z0-9]+)$ [name='user-list']
^ ^users/(?P<pk>[^/.]+)/$ [name='user-detail']
^ ^users/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='user-detail']
^ ^buildings/$ [name='building-list']
^ ^buildings/.(?P<format>[a-z0-9]+)$ [name='building-list']
^ ^buildings/(?P<pk>[^/.]+)/$ [name='building-detail']
^ ^buildings/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='building-detail']
^ ^characters/$ [name='character-list']
^ ^characters/.(?P<format>[a-z0-9]+)$ [name='character-list']
^ ^characters/(?P<pk>[^/.]+)/$ [name='character-detail']
^ ^characters/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='character-detail']
^ ^promotions/$ [name='promotion-list']
^ ^promotions/.(?P<format>[a-z0-9]+)$ [name='promotion-list']
^ ^promotions/(?P<pk>[^/.]+)/$ [name='promotion-detail']
^ ^promotions/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='promotion-detail']
^ ^corporations/$ [name='corporation-list']
^ ^corporations/.(?P<format>[a-z0-9]+)$ [name='corporation-list']
^ ^corporations/(?P<pk>[^/.]+)/$ [name='corporation-detail']
^ ^corporations/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='corporation-detail']
^ ^boroughs/$ [name='borough-list']
^ ^boroughs/.(?P<format>[a-z0-9]+)$ [name='borough-list']
^ ^boroughs/(?P<pk>[^/.]+)/$ [name='borough-detail']
^ ^boroughs/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='borough-detail']
^ ^chapelrys/$ [name='chapelry-list']
^ ^chapelrys/.(?P<format>[a-z0-9]+)$ [name='chapelry-list']
^ ^chapelrys/(?P<pk>[^/.]+)/$ [name='chapelry-detail']
^ ^chapelrys/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='chapelry-detail']
^ ^quadrats/$ [name='quadrat-list']
^ ^quadrats/.(?P<format>[a-z0-9]+)$ [name='quadrat-list']
^ ^quadrats/(?P<pk>[^/.]+)/$ [name='quadrat-detail']
^ ^quadrats/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='quadrat-detail']
^api-auth/
^media\/(?P<path>.*)$
The current URL, article/my-test, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by Roopatratest** [comment]
And clicking the Crypto Kingdom FAQ leads to this:
Using the URLconf defined in ck.urls, Django tried these URL patterns, in this order:
^$ [name='index']
^login/ [name='login']
^login_guest/ [name='loginGuest']
^guest_upgrade/ [name='guestUpgrade']
^signup/ [name='signup']
^logout/ [name='logout']
^chatbox/ [name='chatbox']
^edit/ [name='editCharacter']
^GET/my_character/ [name='getMyCharacter']
^admin/
data/
^wiki/
^map/
GET/\* [name='dispatcher_get']
SET/\* [name='dispatcher_set']
^convert/
^ ^$ [name='api-root']
^ ^.(?P<format>[a-z0-9]+)$ [name='api-root']
^ ^users/$ [name='user-list']
^ ^users/.(?P<format>[a-z0-9]+)$ [name='user-list']
^ ^users/(?P<pk>[^/.]+)/$ [name='user-detail']
^ ^users/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='user-detail']
^ ^buildings/$ [name='building-list']
^ ^buildings/.(?P<format>[a-z0-9]+)$ [name='building-list']
^ ^buildings/(?P<pk>[^/.]+)/$ [name='building-detail']
^ ^buildings/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='building-detail']
^ ^characters/$ [name='character-list']
^ ^characters/.(?P<format>[a-z0-9]+)$ [name='character-list']
^ ^characters/(?P<pk>[^/.]+)/$ [name='character-detail']
^ ^characters/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='character-detail']
^ ^promotions/$ [name='promotion-list']
^ ^promotions/.(?P<format>[a-z0-9]+)$ [name='promotion-list']
^ ^promotions/(?P<pk>[^/.]+)/$ [name='promotion-detail']
^ ^promotions/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='promotion-detail']
^ ^corporations/$ [name='corporation-list']
^ ^corporations/.(?P<format>[a-z0-9]+)$ [name='corporation-list']
^ ^corporations/(?P<pk>[^/.]+)/$ [name='corporation-detail']
^ ^corporations/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='corporation-detail']
^ ^boroughs/$ [name='borough-list']
^ ^boroughs/.(?P<format>[a-z0-9]+)$ [name='borough-list']
^ ^boroughs/(?P<pk>[^/.]+)/$ [name='borough-detail']
^ ^boroughs/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='borough-detail']
^ ^chapelrys/$ [name='chapelry-list']
^ ^chapelrys/.(?P<format>[a-z0-9]+)$ [name='chapelry-list']
^ ^chapelrys/(?P<pk>[^/.]+)/$ [name='chapelry-detail']
^ ^chapelrys/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='chapelry-detail']
^ ^quadrats/$ [name='quadrat-list']
^ ^quadrats/.(?P<format>[a-z0-9]+)$ [name='quadrat-list']
^ ^quadrats/(?P<pk>[^/.]+)/$ [name='quadrat-detail']
^ ^quadrats/(?P<pk>[^/.]+)/.(?P<format>[a-z0-9]+)$ [name='quadrat-detail']
^api-auth/
^media\/(?P<path>.*)$
The current URL, article/my-new-article, didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.

**Comment by ghost** [comment]
Fixed by dev
