### ISSUE TITLE
Login Page too large and no scroll for some browsers

### ISSUE THREAD

**Issue by djjacket** [cryptokingdom/CK_Beta#31]
While viewing the login page with Firefox, the "Enter as visitor" is not visable.

![image](https://cloud.githubusercontent.com/assets/11663298/9251939/c75e96ae-41a3-11e5-8f0c-78bc6b09b31e.png)

**Comment by ghost** [comment]
Fixed by dev

**Comment by djjacket** [comment]
Showing the same issue with the new char page.
![image](https://cloud.githubusercontent.com/assets/11663298/9256499/c20e5d3c-41bd-11e5-9129-67c8bd80c024.png)

**Comment by fluffypony** [comment]
@djjacket changes not deployed yet, I'll deploy it a bit later and we can see if the character page is fixed
